apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-pulse.name" . }}
  labels:
    {{- include "platform-pulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform-pulse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-pulse.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DYNAMODB_TABLE
              value: {{ .Values.dynamodbTable | quote }}
            - name: AWS_REGION
              value: {{ .Values.awsRegion | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
