apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-pulse.name" . }}
  labels:
    {{- include "platform-pulse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    {{- include "platform-pulse.selectorLabels" . | nindent 4 }}
